notifications:
  email:
    - travis-ci@pimcore.org

sudo: false
language: php

php:
  - 7.2

addons:
  mariadb: '10.1'

cache:
  directories:
    - vendor

env:
  global:
    - PIMCORE_ENVIRONMENT=test
    - PIMCORE_TEST=1
    - PIMCORE_TEST_URL=http://pimcore-test.dev
    - PIMCORE_TEST_DB_DSN="mysql://root@localhost/pimcore_test"
    - PIMCORE_TEST_SUITE=cache
    - PIMCORE_TEST_GROUP=cache.core.db

before_install:
  - mysql --version
  - mysql -e "CREATE DATABASE pimcore_test CHARSET=utf8mb4;"

install:
  # add config templates
  - mkdir -p var/config
  - cp .travis/system.template.php var/config/system.php
  - cp app/config/parameters.example.yml app/config/parameters.yml
  - composer install

before_script:
  - .travis/setup-php.sh
  - .travis/setup-functional-tests.sh

script:
  - .travis/run-tests.sh
